version: "3.9"
services:
  api:
    #image: nestjs-luckyapp
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/db
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"

  postgres:
    image: postgres:12.12
    restart: always
    ports:
      - "3001:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
volumes:
  redis:
    driver: local
